PRODENG-1981 fix aws example passing type/vol-size to mods
Mirantis/launchpad_legacy pull request #89
Opened 2022-12-01 17:02 UTC by james-nesbitt

- master/worker/msr modules were not receiving global vars for instance-type and volume-size
- also added json tfvars to the git ignore

Signed-off-by: James Nesbitt <james.r.nesbitt@gmail.com>

2022-12-01 17:02 UTC, james-nesbitt commented
haven't even run tf plan to test it yet

2022-12-01 17:36 UTC, ranyodh approved these changes

2022-12-01 19:45 UTC, sakshisharma84 requested changes

2022-12-01 19:45 UTC, sakshisharma84 commented on examples/terraform/aws/main.tf
> +  worker_type           = var.worker_type
This is already present in line no 62. So, can be removed.

2022-12-01 19:45 UTC, sakshisharma84 commented on examples/terraform/aws/main.tf
> +  worker_type                    = var.worker_type
This is already present in line no 77. Please remove it.

2022-12-02 15:18 UTC, james-nesbitt commented on examples/terraform/aws/main.tf
> +  worker_type           = var.worker_type
good eye. I actually deleted the il lines to keep the same order across all modules (lazy)

2022-12-02 15:19 UTC, james-nesbitt commented on examples/terraform/aws/main.tf
> +  worker_type                    = var.worker_type
good eye. I actually deleted the il lines to keep the same order across all modules (lazy)

2022-12-02 16:13 UTC, sakshisharma84 approved these changes
LGTM!

2022-12-06 14:16 UTC, merged